services:
  - type: web
    name: my-flask-blog
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -b 0.0.0.0:10000 my_blog:app"

    autoDeploy: true
